// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-Uej1O7OCsak20AKN_LEX13lcIrS99A',
    appId: '1:190845488059:web:14b354b18e8fa68dfc929e',
    messagingSenderId: '190845488059',
    projectId: 'authentication-8182b',
    authDomain: 'authentication-8182b.firebaseapp.com',
    storageBucket: 'authentication-8182b.firebasestorage.app',
    measurementId: 'G-ZVFX2NS5CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8j6H0TKbpdbeP6WfU-fQxQDMfprlYN5M',
    appId: '1:190845488059:android:918e894d5e4ae621fc929e',
    messagingSenderId: '190845488059',
    projectId: 'authentication-8182b',
    storageBucket: 'authentication-8182b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDely7Wes_oPYDaTlws-RxOIvoYgGv7Wkc',
    appId: '1:190845488059:ios:9dfd420a765b88b1fc929e',
    messagingSenderId: '190845488059',
    projectId: 'authentication-8182b',
    storageBucket: 'authentication-8182b.firebasestorage.app',
    iosBundleId: 'com.example.trackingUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDely7Wes_oPYDaTlws-RxOIvoYgGv7Wkc',
    appId: '1:190845488059:ios:9dfd420a765b88b1fc929e',
    messagingSenderId: '190845488059',
    projectId: 'authentication-8182b',
    storageBucket: 'authentication-8182b.firebasestorage.app',
    iosBundleId: 'com.example.trackingUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXZeMDG8gXTc9sv79EcPDKMAXelSgmgCk',
    appId: '1:190845488059:web:9348dc766833192efc929e',
    messagingSenderId: '190845488059',
    projectId: 'authentication-8182b',
    authDomain: 'authentication-8182b.firebaseapp.com',
    storageBucket: 'authentication-8182b.firebasestorage.app',
    measurementId: 'G-MRXWFE4PNQ',
  );
}
